### PR TITLE
Added TNEF files support

### PR DESCRIPTION
**Pull request by garanews**
extract the content of TNEF files (such as winmail.dat) and submit the files with the same logic of zip files

### CODE REVIEW

**Comment by doomedraven** [comment]
thanks

**Comment by doomedraven** [comment]
btw can you add check for extraction path of `fullpath = os.path.join(tmp_dir, a.name)` to not overwrite some files? thanks Mister X to point it

**Comment by garanews** [comment]
What do you suggest? Like create each file in a separated subfolder?

**Comment by doomedraven** [comment]
i think the easier is jut to get basename + 

change 
````
+    except:
 +        pass

to

except Exception as e:
    log.error(e)
```

**Comment by garanews** [comment]
I added this https://github.com/doomedraven/cuckoo-modified/pull/24

**Pull request merged**
